name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          name: flber/Pillar 
      - run: cd Pillar
      - run: apt install cargo
      - run: cargo build --release
      - run: cd ../Friend-Site
      - run: ./../Pillar/target/release/pillar build
