name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: git clone https://github.com/flber/Pillar
      - name: Build pillar
        working-directory: ./Pillar
        run: cargo build --release --all-features
      - name: Build site
        working-directory: ./
        run: ./Pillar/target/release/pillar build
      - name: Save Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: html-artifact
          path: public
          
  deploy-production:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download Website Artifact
      uses: actions/download-artifact@v1
      with:
        name: html-artifact
        path: public
