name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: git clone https://github.com/flber/Pillar
      - name: Build pillar
        working-directory: ./Pillar
        run: cargo build --release --all-features
      - name: Build site
        working-directory: ./
        run: ./Pillar/target/release/pillar build
