name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
        with:
          name: flber/Pillar
      - run: ls
      - run: cd pillar
      - run: apt install cargo
      - run: cargo build --release
      - run: cd ..
      - run: ./pillar/target/release/pillar build
